# Nerual network from scratch day1

## Lecture 1

In [16]:
import numpy as np
inputs = [[1.0,2.0,3.0,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]
weights = [[0.2,0.8,-0.5,1],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]
weights2 = [[0.1,-0.14,0.5],
           [-0.5,0.12,-0.33],
           [-0.44,0.73,-0.13]]

biases = [2.0,3.0,0.5]
biases2=[-1,2,-0.5
        ]
inputs_array =  np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
biases2_array = np.array(biases2)
weights2_array = np.array(weights2)


outputs = np.dot(inputs_array,weights_array.T)+biases_array
outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

### Multilayer

In [19]:
import numpy as np
inputs = [[1.0,2.0,3.0,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]
weights = [[0.2,0.8,-0.5,1],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]
weights2 = [[0.1,-0.14,0.5],
           [-0.5,0.12,-0.33],
           [-0.44,0.73,-0.13]]

biases = [2.0,3.0,0.5]
biases2=[-1,2,-0.5
        ]
inputs_array =  np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
biases2_array = np.array(biases2)
weights2_array = np.array(weights2)


outputs_layer1 = np.dot(inputs_array,weights_array.T)+biases_array
outputs_layer2 = np.dot(outputs_layer1,weights2_array.T)+biases2_array
outputs_layer2

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])


## Practice

In [24]:
import numpy as np

inputs = np.array([
    [1.0, 2.0, 3.0],
    [2.0, 5.0, -1.0],
    [-1.5, 2.7, 3.3]
])

# Input (3) -> Hidden Layer 1 (4)
weights1 = np.array([
    [ 0.20,  0.80, -0.50],
    [ 0.50, -0.91,  0.26],
    [-0.26, -0.27,  0.17],
    [ 0.87, -0.12,  0.42]
])

biases1 = np.array([
    2.0,
    3.0,
    0.5,
   -1.0
])

# Hidden Layer 1 (4) -> Hidden Layer 2 (4)
weights2 = np.array([
    [ 0.10, -0.14,  0.50, -0.20],
    [-0.50,  0.12, -0.33,  0.40],
    [-0.44,  0.73, -0.13,  0.60],
    [ 0.25, -0.81,  0.37, -0.10]
])

biases2 = np.array([
   -1.0,
    2.0,
   -0.5,
    1.5
])

# Hidden Layer 2 (4) -> Output (1)
weights3 = np.array([
    [0.30, -0.60, 0.80, -0.25]
])

biases3 = np.array([
    0.75
])


output_layer1 = np.dot(inputs,weights1.T)+biases1
output_layer2 = np.dot(output_layer1,weights2.T)+biases2
output = np.dot(output_layer2,weights3.T)+biases3
output

array([[ 0.149265 ],
       [-2.943485 ],
       [-1.4193795]])